name: Game Theory. Ecology. Evolution.
description: Minisymposium  in ECMTB 2014
meta_description: "Game Theory. Ecology. Evolution."

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
