name: Game Theory in Ecology and Evolution.
description: Minisymposium  in ECMTB 2014
meta_description: "Game Theory in Ecology and Evolution."

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://evolgamesecmtb2014.github.io'
author:         'Chaitanya Gokhale'